// <auto-generated />
using System;
using Entities.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kemet.Intrastructure.Migrations
{
    [DbContext(typeof(KemetDbContext))]
    [Migration("20250722185822_Make_DeliveryCompany_nullable")]
    partial class Make_DeliveryCompany_nullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AddressId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<int>("GovernorateId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AddressId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("GovernorateId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "بناطيل جبردين"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "بناطيل جينز"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "جيبة جينز"
                        });
                });

            modelBuilder.Entity("Entities.Models.Color", b =>
                {
                    b.Property<int>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ColorId"));

                    b.Property<string>("HexaCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ColorId");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            ColorId = 1,
                            HexaCode = "#000000",
                            Name = "اسود"
                        },
                        new
                        {
                            ColorId = 2,
                            HexaCode = "#000080",
                            Name = "كحلى"
                        },
                        new
                        {
                            ColorId = 3,
                            HexaCode = "#654321",
                            Name = "بنى غامق"
                        },
                        new
                        {
                            ColorId = 4,
                            HexaCode = "#A9A9A9",
                            Name = "رمادى غامق"
                        },
                        new
                        {
                            ColorId = 5,
                            HexaCode = "#808000",
                            Name = "زيتونى"
                        },
                        new
                        {
                            ColorId = 6,
                            HexaCode = "#C0C0C0",
                            Name = "فضي"
                        },
                        new
                        {
                            ColorId = 7,
                            HexaCode = "#C19A6B",
                            Name = "جملي"
                        },
                        new
                        {
                            ColorId = 8,
                            HexaCode = "#F5F5DC",
                            Name = "بيج"
                        });
                });

            modelBuilder.Entity("Entities.Models.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Entities.Models.DeliveryCompany", b =>
                {
                    b.Property<int>("DeliveryCompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeliveryCompanyId"));

                    b.Property<DateTime>("DialingWithItFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DeliveryCompanyId");

                    b.ToTable("DeliveryCompanies");
                });

            modelBuilder.Entity("Entities.Models.DeliveryCostPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveryCompanyId")
                        .HasColumnType("integer");

                    b.Property<int?>("DeliveryPaymentStatusId")
                        .HasColumnType("integer");

                    b.Property<int?>("GovernorateDeliveryCompanyId")
                        .HasColumnType("integer");

                    b.Property<int>("GovernorateId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PaidByCustomer")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PaidToCompany")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryCompanyId");

                    b.HasIndex("DeliveryPaymentStatusId");

                    b.HasIndex("GovernorateDeliveryCompanyId");

                    b.HasIndex("GovernorateId");

                    b.HasIndex("OrderId");

                    b.ToTable("DeliveryCostPayments");
                });

            modelBuilder.Entity("Entities.Models.DeliveryPaymentStatus", b =>
                {
                    b.Property<int>("DeliveryPaymentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeliveryPaymentStatusId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DeliveryPaymentStatusId");

                    b.ToTable("DeliveryPaymentStatuses");

                    b.HasData(
                        new
                        {
                            DeliveryPaymentStatusId = 1,
                            Description = "Delivery cost has been fully collected.",
                            Name = "Full Paid"
                        },
                        new
                        {
                            DeliveryPaymentStatusId = 2,
                            Description = "Only part of the delivery cost has been collected.",
                            Name = "Partially Paid"
                        },
                        new
                        {
                            DeliveryPaymentStatusId = 3,
                            Description = "Delivery cost is pending; payment has not been fully collected.",
                            Name = "Pending"
                        },
                        new
                        {
                            DeliveryPaymentStatusId = 4,
                            Description = "Delivery cost has not been collected at all.",
                            Name = "Unpaid"
                        });
                });

            modelBuilder.Entity("Entities.Models.DeliveryTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Difference")
                        .HasColumnType("numeric");

                    b.Property<int>("GovernorateDeliveryCompanyId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GovernorateDeliveryCompanyId");

                    b.HasIndex("OrderId");

                    b.ToTable("DeliveryTransactions");
                });

            modelBuilder.Entity("Entities.Models.Governorate", b =>
                {
                    b.Property<int>("GovernorateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GovernorateId"));

                    b.Property<bool>("IsAvailableToDeliver")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GovernorateId");

                    b.ToTable("Governorates");

                    b.HasData(
                        new
                        {
                            GovernorateId = 1,
                            IsAvailableToDeliver = true,
                            Name = "القاهرة"
                        },
                        new
                        {
                            GovernorateId = 2,
                            IsAvailableToDeliver = true,
                            Name = "الجيزة"
                        },
                        new
                        {
                            GovernorateId = 3,
                            IsAvailableToDeliver = true,
                            Name = "الإسكندرية"
                        },
                        new
                        {
                            GovernorateId = 4,
                            IsAvailableToDeliver = true,
                            Name = "الدقهلية"
                        },
                        new
                        {
                            GovernorateId = 5,
                            IsAvailableToDeliver = true,
                            Name = "البحر الأحمر"
                        },
                        new
                        {
                            GovernorateId = 6,
                            IsAvailableToDeliver = true,
                            Name = "البحيرة"
                        },
                        new
                        {
                            GovernorateId = 7,
                            IsAvailableToDeliver = true,
                            Name = "الفيوم"
                        },
                        new
                        {
                            GovernorateId = 8,
                            IsAvailableToDeliver = true,
                            Name = "الغربية"
                        },
                        new
                        {
                            GovernorateId = 9,
                            IsAvailableToDeliver = true,
                            Name = "الشرقية"
                        },
                        new
                        {
                            GovernorateId = 10,
                            IsAvailableToDeliver = true,
                            Name = "الإسماعيلية"
                        },
                        new
                        {
                            GovernorateId = 11,
                            IsAvailableToDeliver = true,
                            Name = "المنوفية"
                        },
                        new
                        {
                            GovernorateId = 12,
                            IsAvailableToDeliver = true,
                            Name = "المنيا"
                        },
                        new
                        {
                            GovernorateId = 13,
                            IsAvailableToDeliver = true,
                            Name = "القليوبية"
                        },
                        new
                        {
                            GovernorateId = 14,
                            IsAvailableToDeliver = true,
                            Name = "الوادي الجديد"
                        },
                        new
                        {
                            GovernorateId = 15,
                            IsAvailableToDeliver = true,
                            Name = "السويس"
                        },
                        new
                        {
                            GovernorateId = 16,
                            IsAvailableToDeliver = true,
                            Name = "أسوان"
                        },
                        new
                        {
                            GovernorateId = 17,
                            IsAvailableToDeliver = true,
                            Name = "أسيوط"
                        },
                        new
                        {
                            GovernorateId = 18,
                            IsAvailableToDeliver = true,
                            Name = "بني سويف"
                        },
                        new
                        {
                            GovernorateId = 19,
                            IsAvailableToDeliver = true,
                            Name = "بورسعيد"
                        },
                        new
                        {
                            GovernorateId = 20,
                            IsAvailableToDeliver = true,
                            Name = "دمياط"
                        },
                        new
                        {
                            GovernorateId = 21,
                            IsAvailableToDeliver = true,
                            Name = "كفر الشيخ"
                        },
                        new
                        {
                            GovernorateId = 22,
                            IsAvailableToDeliver = true,
                            Name = "مطروح"
                        },
                        new
                        {
                            GovernorateId = 23,
                            IsAvailableToDeliver = true,
                            Name = "الأقصر"
                        },
                        new
                        {
                            GovernorateId = 24,
                            IsAvailableToDeliver = true,
                            Name = "قنا"
                        },
                        new
                        {
                            GovernorateId = 25,
                            IsAvailableToDeliver = true,
                            Name = "سوهاج"
                        },
                        new
                        {
                            GovernorateId = 26,
                            IsAvailableToDeliver = true,
                            Name = "جنوب سيناء"
                        },
                        new
                        {
                            GovernorateId = 27,
                            IsAvailableToDeliver = true,
                            Name = "شمال سيناء"
                        });
                });

            modelBuilder.Entity("Entities.Models.GovernorateDelivery", b =>
                {
                    b.Property<int>("GovernorateDeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GovernorateDeliveryId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DeliveryCost")
                        .HasColumnType("numeric");

                    b.Property<int>("GovernorateId")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("GovernorateDeliveryId");

                    b.HasIndex("GovernorateId");

                    b.ToTable("GovernorateDelivery");

                    b.HasData(
                        new
                        {
                            GovernorateDeliveryId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GovernorateId = 1
                        },
                        new
                        {
                            GovernorateDeliveryId = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GovernorateId = 2
                        },
                        new
                        {
                            GovernorateDeliveryId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GovernorateId = 3
                        },
                        new
                        {
                            GovernorateDeliveryId = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GovernorateId = 4
                        },
                        new
                        {
                            GovernorateDeliveryId = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GovernorateId = 5
                        },
                        new
                        {
                            GovernorateDeliveryId = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GovernorateId = 6
                        },
                        new
                        {
                            GovernorateDeliveryId = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GovernorateId = 7
                        },
                        new
                        {
                            GovernorateDeliveryId = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GovernorateId = 8
                        },
                        new
                        {
                            GovernorateDeliveryId = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GovernorateId = 9
                        },
                        new
                        {
                            GovernorateDeliveryId = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GovernorateId = 10
                        },
                        new
                        {
                            GovernorateDeliveryId = 12,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GovernorateId = 11
                        },
                        new
                        {
                            GovernorateDeliveryId = 13,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GovernorateId = 12
                        },
                        new
                        {
                            GovernorateDeliveryId = 14,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GovernorateId = 13
                        },
                        new
                        {
                            GovernorateDeliveryId = 15,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GovernorateId = 14
                        },
                        new
                        {
                            GovernorateDeliveryId = 16,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GovernorateId = 15
                        },
                        new
                        {
                            GovernorateDeliveryId = 17,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GovernorateId = 16
                        },
                        new
                        {
                            GovernorateDeliveryId = 18,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GovernorateId = 17
                        },
                        new
                        {
                            GovernorateDeliveryId = 19,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GovernorateId = 18
                        },
                        new
                        {
                            GovernorateDeliveryId = 20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GovernorateId = 19
                        },
                        new
                        {
                            GovernorateDeliveryId = 21,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GovernorateId = 20
                        },
                        new
                        {
                            GovernorateDeliveryId = 22,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GovernorateId = 21
                        },
                        new
                        {
                            GovernorateDeliveryId = 23,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GovernorateId = 22
                        },
                        new
                        {
                            GovernorateDeliveryId = 24,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GovernorateId = 23
                        },
                        new
                        {
                            GovernorateDeliveryId = 25,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GovernorateId = 24
                        },
                        new
                        {
                            GovernorateDeliveryId = 26,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GovernorateId = 25
                        },
                        new
                        {
                            GovernorateDeliveryId = 27,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GovernorateId = 26
                        },
                        new
                        {
                            GovernorateDeliveryId = 28,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GovernorateId = 27
                        });
                });

            modelBuilder.Entity("Entities.Models.GovernorateDeliveryCompany", b =>
                {
                    b.Property<int>("GovernorateDeliveryCompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GovernorateDeliveryCompanyId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveryCompanyId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("DeliveryCost")
                        .HasColumnType("numeric");

                    b.Property<int>("GovernorateId")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("GovernorateDeliveryCompanyId");

                    b.HasIndex("DeliveryCompanyId");

                    b.HasIndex("GovernorateId");

                    b.ToTable("GovernorateDeliveryCompanies");
                });

            modelBuilder.Entity("Entities.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<int?>("DeliveryCompanyId")
                        .HasColumnType("integer");

                    b.Property<int?>("GovernorateDeliveryCompanyId")
                        .HasColumnType("integer");

                    b.Property<int?>("OrderReceiptStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("integer");

                    b.Property<decimal>("OrderTotalPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductQuantityPriceId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OrderId");

                    b.HasIndex("AddressId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeliveryCompanyId");

                    b.HasIndex("GovernorateDeliveryCompanyId");

                    b.HasIndex("OrderReceiptStatusId");

                    b.HasIndex("OrderStatusId");

                    b.HasIndex("ProductQuantityPriceId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Entities.Models.OrderInvoice", b =>
                {
                    b.Property<int>("OrderInvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderInvoiceId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ReturnId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("OrderInvoiceId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ReturnId");

                    b.ToTable("OrderInvoices");
                });

            modelBuilder.Entity("Entities.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int?>("ReturnId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("ReturnId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Entities.Models.OrderReceiptNote", b =>
                {
                    b.Property<int>("OrderReceiptNotesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderReceiptNotesId"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OrderReceiptNotesId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("OrderReceiptNotes");
                });

            modelBuilder.Entity("Entities.Models.OrderReceiptStatus", b =>
                {
                    b.Property<int>("OrderReceiptStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderReceiptStatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OrderReceiptStatusId1")
                        .HasColumnType("integer");

                    b.HasKey("OrderReceiptStatusId");

                    b.HasIndex("OrderReceiptStatusId1");

                    b.ToTable("OrderReceiptStatuses");

                    b.HasData(
                        new
                        {
                            OrderReceiptStatusId = 1,
                            Name = "Fully Receipt"
                        },
                        new
                        {
                            OrderReceiptStatusId = 2,
                            Name = "Partially Receipt"
                        },
                        new
                        {
                            OrderReceiptStatusId = 3,
                            Name = "Refused Receipt"
                        },
                        new
                        {
                            OrderReceiptStatusId = 4,
                            Name = "Attempt Failed"
                        });
                });

            modelBuilder.Entity("Entities.Models.OrderStatus", b =>
                {
                    b.Property<int>("OrderStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderStatusId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OrderStatusId");

                    b.ToTable("OrderStatuses");

                    b.HasData(
                        new
                        {
                            OrderStatusId = 1,
                            Description = "Order is pending.",
                            Name = "Pending"
                        },
                        new
                        {
                            OrderStatusId = 2,
                            Description = "Order is being processed.",
                            Name = "Processing"
                        },
                        new
                        {
                            OrderStatusId = 3,
                            Description = "Order has been shipped.",
                            Name = "Shipped"
                        },
                        new
                        {
                            OrderStatusId = 4,
                            Description = "Order has been delivered.",
                            Name = "Delivered"
                        },
                        new
                        {
                            OrderStatusId = 5,
                            Description = "Order has been cancelled by customer.",
                            Name = "Cancelled By Customer"
                        },
                        new
                        {
                            OrderStatusId = 6,
                            Description = "Order has been cancelled by admin.",
                            Name = "Cancelled By Admin"
                        },
                        new
                        {
                            OrderStatusId = 7,
                            Description = "Order has been refunded.",
                            Name = "Refunded"
                        });
                });

            modelBuilder.Entity("Entities.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("integer");

                    b.HasKey("PaymentId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PaymentTypeId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Entities.Models.PaymentType", b =>
                {
                    b.Property<int>("PaymentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PaymentTypeId");

                    b.ToTable("PaymentTypes");
                });

            modelBuilder.Entity("Entities.Models.Price", b =>
                {
                    b.Property<int>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PriceId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MaximumPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinimumPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartFrom")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PriceId");

                    b.HasIndex("ProductId");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Entities.Models.ProductQuantityPrice", b =>
                {
                    b.Property<int>("ProductQuantityPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductQuantityPriceId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("ProductQuantityPriceId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductQuantityPrices");
                });

            modelBuilder.Entity("Entities.Models.ProductVariant", b =>
                {
                    b.Property<int>("ProductVariantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductVariantId"));

                    b.Property<int>("ColorId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("SizeId")
                        .HasColumnType("integer");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("ProductVariantId");

                    b.HasIndex("ColorId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SizeId");

                    b.ToTable("ProductVariants");
                });

            modelBuilder.Entity("Entities.Models.Return", b =>
                {
                    b.Property<int>("ReturnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReturnId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HandledByUserId")
                        .HasColumnType("integer");

                    b.Property<Guid>("HandledByUserId1")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ReturnedQuantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalRefundedAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalReturnAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ReturnId");

                    b.HasIndex("HandledByUserId1");

                    b.HasIndex("OrderId");

                    b.ToTable("Returns");
                });

            modelBuilder.Entity("Entities.Models.ReturnItem", b =>
                {
                    b.Property<int>("ReturnItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReturnItemId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ItemTotalPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ItemUnitPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("integer");

                    b.Property<short>("ProcessedRefundAmount")
                        .HasColumnType("smallint");

                    b.Property<short>("RequestedRefundAmount")
                        .HasColumnType("smallint");

                    b.Property<int>("ReturnId")
                        .HasColumnType("integer");

                    b.Property<string>("ReturnNotes")
                        .HasColumnType("text");

                    b.Property<int>("ReturnStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("ReturnStatusId1")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ReturnItemId");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("ReturnId");

                    b.HasIndex("ReturnStatusId");

                    b.HasIndex("ReturnStatusId1");

                    b.ToTable("ReturnItems");
                });

            modelBuilder.Entity("Entities.Models.ReturnStatus", b =>
                {
                    b.Property<int>("ReturnStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReturnStatusId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ReturnStatusId");

                    b.ToTable("ReturnStatuses");

                    b.HasData(
                        new
                        {
                            ReturnStatusId = 1,
                            Description = "Delivery person has the items",
                            Name = "With Delivery Company"
                        },
                        new
                        {
                            ReturnStatusId = 2,
                            Description = "Delivery company bringing items back",
                            Name = "In Transit"
                        },
                        new
                        {
                            ReturnStatusId = 3,
                            Description = "Items physically returned to the business.",
                            Name = "Received"
                        },
                        new
                        {
                            ReturnStatusId = 4,
                            Description = "Checking item condition.",
                            Name = "Under Inspection"
                        },
                        new
                        {
                            ReturnStatusId = 5,
                            Description = "Return item is restocked.",
                            Name = "Restocked"
                        },
                        new
                        {
                            ReturnStatusId = 6,
                            Description = "Return item is disposed.",
                            Name = "Disposed"
                        },
                        new
                        {
                            ReturnStatusId = 7,
                            Description = "Return item is lost.",
                            Name = "Lost"
                        });
                });

            modelBuilder.Entity("Entities.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Size", b =>
                {
                    b.Property<int>("SizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SizeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SizeId");

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            SizeId = 1,
                            Name = "30"
                        },
                        new
                        {
                            SizeId = 2,
                            Name = "32"
                        },
                        new
                        {
                            SizeId = 3,
                            Name = "34"
                        },
                        new
                        {
                            SizeId = 4,
                            Name = "36"
                        },
                        new
                        {
                            SizeId = 5,
                            Name = "38"
                        },
                        new
                        {
                            SizeId = 6,
                            Name = "40"
                        },
                        new
                        {
                            SizeId = 7,
                            Name = "42"
                        },
                        new
                        {
                            SizeId = 8,
                            Name = "44"
                        },
                        new
                        {
                            SizeId = 9,
                            Name = "46"
                        },
                        new
                        {
                            SizeId = 10,
                            Name = "48"
                        },
                        new
                        {
                            SizeId = 11,
                            Name = "50"
                        },
                        new
                        {
                            SizeId = 12,
                            Name = "52"
                        },
                        new
                        {
                            SizeId = 13,
                            Name = "54"
                        },
                        new
                        {
                            SizeId = 14,
                            Name = "56"
                        },
                        new
                        {
                            SizeId = 15,
                            Name = "58"
                        },
                        new
                        {
                            SizeId = 16,
                            Name = "60"
                        },
                        new
                        {
                            SizeId = 17,
                            Name = "62"
                        },
                        new
                        {
                            SizeId = 18,
                            Name = "64"
                        },
                        new
                        {
                            SizeId = 19,
                            Name = "S"
                        },
                        new
                        {
                            SizeId = 20,
                            Name = "M"
                        },
                        new
                        {
                            SizeId = 21,
                            Name = "L"
                        },
                        new
                        {
                            SizeId = 22,
                            Name = "XL"
                        },
                        new
                        {
                            SizeId = 23,
                            Name = "XXL"
                        },
                        new
                        {
                            SizeId = 24,
                            Name = "XXXL"
                        });
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Address", b =>
                {
                    b.HasOne("Entities.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Governorate", "Governorate")
                        .WithMany()
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("Entities.Models.Customer", b =>
                {
                    b.HasOne("Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Models.DeliveryCostPayment", b =>
                {
                    b.HasOne("Entities.Models.DeliveryCompany", "DeliveryCompany")
                        .WithMany()
                        .HasForeignKey("DeliveryCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.DeliveryPaymentStatus", "DeliveryPaymentStatus")
                        .WithMany()
                        .HasForeignKey("DeliveryPaymentStatusId");

                    b.HasOne("Entities.Models.GovernorateDeliveryCompany", "GovernorateDeliveryCompany")
                        .WithMany()
                        .HasForeignKey("GovernorateDeliveryCompanyId");

                    b.HasOne("Entities.Models.Governorate", "Governorate")
                        .WithMany()
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryCompany");

                    b.Navigation("DeliveryPaymentStatus");

                    b.Navigation("Governorate");

                    b.Navigation("GovernorateDeliveryCompany");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Entities.Models.DeliveryTransaction", b =>
                {
                    b.HasOne("Entities.Models.GovernorateDeliveryCompany", "GovernorateDeliveryCompany")
                        .WithMany()
                        .HasForeignKey("GovernorateDeliveryCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GovernorateDeliveryCompany");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Entities.Models.GovernorateDelivery", b =>
                {
                    b.HasOne("Entities.Models.Governorate", "Governorate")
                        .WithMany("GovernoratesDelivery")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("Entities.Models.GovernorateDeliveryCompany", b =>
                {
                    b.HasOne("Entities.Models.DeliveryCompany", "DeliveryCompany")
                        .WithMany("GovernoratesDeliveryCompany")
                        .HasForeignKey("DeliveryCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Governorate", "Governorate")
                        .WithMany("GovernoratesDeliveryCompany")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryCompany");

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("Entities.Models.Order", b =>
                {
                    b.HasOne("Entities.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.DeliveryCompany", "DeliveryCompany")
                        .WithMany("Orders")
                        .HasForeignKey("DeliveryCompanyId");

                    b.HasOne("Entities.Models.GovernorateDeliveryCompany", "GovernorateDeliveryCompany")
                        .WithMany("Orders")
                        .HasForeignKey("GovernorateDeliveryCompanyId");

                    b.HasOne("Entities.Models.OrderReceiptStatus", "OrderReceiptStatus")
                        .WithMany()
                        .HasForeignKey("OrderReceiptStatusId");

                    b.HasOne("Entities.Models.OrderStatus", "OrderStatus")
                        .WithMany()
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.ProductQuantityPrice", "ProductQuantityPrice")
                        .WithMany()
                        .HasForeignKey("ProductQuantityPriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Customer");

                    b.Navigation("DeliveryCompany");

                    b.Navigation("GovernorateDeliveryCompany");

                    b.Navigation("OrderReceiptStatus");

                    b.Navigation("OrderStatus");

                    b.Navigation("ProductQuantityPrice");
                });

            modelBuilder.Entity("Entities.Models.OrderInvoice", b =>
                {
                    b.HasOne("Entities.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Return", "Return")
                        .WithMany()
                        .HasForeignKey("ReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Return");
                });

            modelBuilder.Entity("Entities.Models.OrderItem", b =>
                {
                    b.HasOne("Entities.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Return", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("ReturnId");

                    b.Navigation("Order");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Entities.Models.OrderReceiptNote", b =>
                {
                    b.HasOne("Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Models.OrderReceiptStatus", b =>
                {
                    b.HasOne("Entities.Models.OrderReceiptStatus", null)
                        .WithMany("OrderReceiptStatuses")
                        .HasForeignKey("OrderReceiptStatusId1");
                });

            modelBuilder.Entity("Entities.Models.Payment", b =>
                {
                    b.HasOne("Entities.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.PaymentType", "PaymentType")
                        .WithMany()
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("PaymentType");
                });

            modelBuilder.Entity("Entities.Models.Price", b =>
                {
                    b.HasOne("Entities.Models.Product", "Product")
                        .WithMany("Prices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.HasOne("Entities.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Entities.Models.ProductQuantityPrice", b =>
                {
                    b.HasOne("Entities.Models.Product", "Product")
                        .WithMany("QuantityPrices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Entities.Models.ProductVariant", b =>
                {
                    b.HasOne("Entities.Models.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Size", "Size")
                        .WithMany("ProductVariants")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Product");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("Entities.Models.Return", b =>
                {
                    b.HasOne("Entities.Models.User", "HandledByUser")
                        .WithMany()
                        .HasForeignKey("HandledByUserId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HandledByUser");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Entities.Models.ReturnItem", b =>
                {
                    b.HasOne("Entities.Models.OrderItem", "OrderItem")
                        .WithMany()
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Return", "Return")
                        .WithMany("ReturnItems")
                        .HasForeignKey("ReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.ReturnStatus", null)
                        .WithMany("ReturnItems")
                        .HasForeignKey("ReturnStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.ReturnStatus", "ReturnStatus")
                        .WithMany()
                        .HasForeignKey("ReturnStatusId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderItem");

                    b.Navigation("Return");

                    b.Navigation("ReturnStatus");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Entities.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Entities.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.DeliveryCompany", b =>
                {
                    b.Navigation("GovernoratesDeliveryCompany");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Entities.Models.Governorate", b =>
                {
                    b.Navigation("GovernoratesDelivery");

                    b.Navigation("GovernoratesDeliveryCompany");
                });

            modelBuilder.Entity("Entities.Models.GovernorateDeliveryCompany", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Entities.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Entities.Models.OrderReceiptStatus", b =>
                {
                    b.Navigation("OrderReceiptStatuses");
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Navigation("Prices");

                    b.Navigation("QuantityPrices");
                });

            modelBuilder.Entity("Entities.Models.Return", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("ReturnItems");
                });

            modelBuilder.Entity("Entities.Models.ReturnStatus", b =>
                {
                    b.Navigation("ReturnItems");
                });

            modelBuilder.Entity("Entities.Models.Size", b =>
                {
                    b.Navigation("ProductVariants");
                });
#pragma warning restore 612, 618
        }
    }
}
