services:
  api:
    build:
      context: ./API/
      dockerfile: Dockerfile.dev
    container_name: Tarzy_api
    ports:
      - "5255:8080"
    volumes:
      - ./API/:/src
      - tarzy_dotnet_cache:/root/.nuget/packages
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - database
  client:
    build:
      context: ./Client/
      dockerfile: Dockerfile.dev
    container_name: Tarzy_client
    ports:
      - "3000:3000"
    volumes:
      - ./Client:/app
      - tarzy_node_modules:/app/node_modules 
    environment:
      - CHOKIDAR_USEPOLLING=true   # for hot reload in Docker
    depends_on:
      - api


  database:
    image: postgres:17 
    container_name: Tarzy_postgreSQL_db
    environment:
      POSTGRES_USER: kemet
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: kemetdb
    ports:
      - "6800:5432"
    volumes:
      - tarzy_postgres_data:/var/lib/postgresql/data

volumes:
  tarzy_dotnet_cache:
  tarzy_postgres_data:
  tarzy_node_modules:
